seed=0
master_port=37336

CUDA_VISIBLE_DEVICES=0 python ../train.py \
    method=PERACT_BC \
    rlbench.tasks=[open_jar] \
    rlbench.task_name=open_jar_ours_vlm_real_robot_v4_acting \
    rlbench.cameras=[front] \
    rlbench.demos=20 \
    rlbench.demo_path=$PERACT_ROOT/data/train/open_jar_2024_06_14_v1_acting_stabilizing_trimmed \
    rlbench.scene_bounds=[-1.0,-1.0,-0.5,1.0,1.0,1.5] \
    rlbench.camera_resolution=[1280,1280] \
    replay.batch_size=1 \
    replay.path=/tmp/replay_${master_port} \
    replay.max_parallel_processes=16 \
    method.voxel_sizes=[50] \
    method.voxel_patch_size=5 \
    method.voxel_patch_stride=5 \
    method.num_latents=2048 \
    method.transform_augmentation.apply_se3=True \
    method.transform_augmentation.aug_rpy=[0.0,0.0,45.0] \
    method.pos_encoding_with_lang=True \
    method.which_arm=dominant \
    method.arm_pred_loss=True \
    method.is_real_robot=True \
    method.crop_target_obj_voxel=True \
    method.crop_radius=0.5 \
    method.stopped_buffer_timesteps_overwrite=15 \
    method.keypoint_discovery_no_duplicate=True \
    framework.training_iterations=1000000 \
    framework.num_weights_to_keep=100 \
    framework.start_seed=${seed} \
    framework.log_freq=1000 \
    framework.save_freq=10000 \
    framework.logdir=$PERACT_ROOT/logs/ \
    framework.csv_logging=True \
    framework.tensorboard_logging=False \
    framework.wandb_logging=True \
    framework.load_existing_weights=True \
    ddp.num_devices=1 \
    ddp.master_port=${master_port}